version: '3.4'
services:
  ism:
    build:
      context: ./scr/InternetSpeedMonitor/
      dockerfile: Dockerfile
    environment:
      - TAGHOST=docker
      - DB_HOST=db:5432
      - DB_USER=ism
      - DB_PASSWORD=ism 
      - DB_NAME=ism
      
  db:
    image: postgres:14
    volumes:
    - ./db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ism
      - POSTGRES_PASSWORD=ism
      - POSTGRES_DB=ism
    ports:
      - 5333:5432
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
